<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CurrenciesSeeder extends Seeder
{
    public function run()
    {
        $data = [
            ['currency_code' => 'AED', 'conversion_from_base' => 3.6725, 'conversion_to_base' => 0.2723],
            ['currency_code' => 'AFN', 'conversion_from_base' => 77.50, 'conversion_to_base' => 0.0129],
            ['currency_code' => 'ALL', 'conversion_from_base' => 106.40, 'conversion_to_base' => 0.0094],
            ['currency_code' => 'AMD', 'conversion_from_base' => 480.0, 'conversion_to_base' => 0.0021],
            ['currency_code' => 'ANG', 'conversion_from_base' => 1.79, 'conversion_to_base' => 0.5590],
            ['currency_code' => 'AOA', 'conversion_from_base' => 650.0, 'conversion_to_base' => 0.0015],
            ['currency_code' => 'ARS', 'conversion_from_base' => 350.0, 'conversion_to_base' => 0.0029],
            ['currency_code' => 'AUD', 'conversion_from_base' => 1.34, 'conversion_to_base' => 0.7463],
            ['currency_code' => 'AWG', 'conversion_from_base' => 1.80, 'conversion_to_base' => 0.5556],
            ['currency_code' => 'AZN', 'conversion_from_base' => 1.70, 'conversion_to_base' => 0.5882],
            ['currency_code' => 'BAM', 'conversion_from_base' => 1.60, 'conversion_to_base' => 0.6250],
            ['currency_code' => 'BBD', 'conversion_from_base' => 2.00, 'conversion_to_base' => 0.5000],
            ['currency_code' => 'BDT', 'conversion_from_base' => 85.0, 'conversion_to_base' => 0.0118],
            ['currency_code' => 'BGN', 'conversion_from_base' => 1.65, 'conversion_to_base' => 0.6061],
            ['currency_code' => 'BHD', 'conversion_from_base' => 0.38, 'conversion_to_base' => 2.6316],
            ['currency_code' => 'BIF', 'conversion_from_base' => 2000.0, 'conversion_to_base' => 0.0005],
            ['currency_code' => 'BMD', 'conversion_from_base' => 1.0, 'conversion_to_base' => 1.0],
            ['currency_code' => 'BND', 'conversion_from_base' => 1.34, 'conversion_to_base' => 0.7463],
            ['currency_code' => 'BOB', 'conversion_from_base' => 6.91, 'conversion_to_base' => 0.1447],
            ['currency_code' => 'BOV', 'conversion_from_base' => 1.0, 'conversion_to_base' => 1.0],
            ['currency_code' => 'BRL', 'conversion_from_base' => 5.15, 'conversion_to_base' => 0.1942],
            ['currency_code' => 'BSD', 'conversion_from_base' => 1.0, 'conversion_to_base' => 1.0],
            ['currency_code' => 'BTN', 'conversion_from_base' => 74.0, 'conversion_to_base' => 0.0135],
            ['currency_code' => 'BWP', 'conversion_from_base' => 11.0, 'conversion_to_base' => 0.0909],
            ['currency_code' => 'BYN', 'conversion_from_base' => 2.5, 'conversion_to_base' => 0.4000],
            ['currency_code' => 'BZD', 'conversion_from_base' => 2.0, 'conversion_to_base' => 0.5000],
            ['currency_code' => 'CAD', 'conversion_from_base' => 1.25, 'conversion_to_base' => 0.8000],
            ['currency_code' => 'CDF', 'conversion_from_base' => 2000.0, 'conversion_to_base' => 0.0005],
            ['currency_code' => 'CHE', 'conversion_from_base' => 0.99, 'conversion_to_base' => 1.0101],
            ['currency_code' => 'CHF', 'conversion_from_base' => 0.91, 'conversion_to_base' => 1.0989],
            ['currency_code' => 'CHW', 'conversion_from_base' => 0.91, 'conversion_to_base' => 1.0989],
            ['currency_code' => 'CLF', 'conversion_from_base' => 0.024, 'conversion_to_base' => 41.6667],
            ['currency_code' => 'CLP', 'conversion_from_base' => 800.0, 'conversion_to_base' => 0.00125],
            ['currency_code' => 'CNY', 'conversion_from_base' => 6.47, 'conversion_to_base' => 0.1546],
            ['currency_code' => 'COP', 'conversion_from_base' => 3800.0, 'conversion_to_base' => 0.0002632],
            ['currency_code' => 'COU', 'conversion_from_base' => 1.0, 'conversion_to_base' => 1.0],
            ['currency_code' => 'CRC', 'conversion_from_base' => 610.0, 'conversion_to_base' => 0.0016393],
            ['currency_code' => 'CUC', 'conversion_from_base' => 1.0, 'conversion_to_base' => 1.0],
            ['currency_code' => 'CUP', 'conversion_from_base' => 25.0, 'conversion_to_base' => 0.0400],
            ['currency_code' => 'CVE', 'conversion_from_base' => 100.0, 'conversion_to_base' => 0.0100],
            ['currency_code' => 'CZK', 'conversion_from_base' => 21.5, 'conversion_to_base' => 0.0465],
            ['currency_code' => 'DJF', 'conversion_from_base' => 177.72, 'conversion_to_base' => 0.0056],
            ['currency_code' => 'DKK', 'conversion_from_base' => 6.3, 'conversion_to_base' => 0.1587],
            ['currency_code' => 'DOP', 'conversion_from_base' => 57.0, 'conversion_to_base' => 0.0175],
            ['currency_code' => 'DZD', 'conversion_from_base' => 135.0, 'conversion_to_base' => 0.0074],
            ['currency_code' => 'EGP', 'conversion_from_base' => 15.7, 'conversion_to_base' => 0.0637],
            ['currency_code' => 'ERN', 'conversion_from_base' => 15.0, 'conversion_to_base' => 0.0667],
            ['currency_code' => 'ETB', 'conversion_from_base' => 42.0, 'conversion_to_base' => 0.0238],
            ['currency_code' => 'EUR', 'conversion_from_base' => 0.85, 'conversion_to_base' => 1.1765],
            ['currency_code' => 'FJD', 'conversion_from_base' => 2.15, 'conversion_to_base' => 0.4651],
            ['currency_code' => 'FKP', 'conversion_from_base' => 0.73, 'conversion_to_base' => 1.3699],
            ['currency_code' => 'GBP', 'conversion_from_base' => 0.73, 'conversion_to_base' => 1.3699],
            ['currency_code' => 'GEL', 'conversion_from_base' => 3.1, 'conversion_to_base' => 0.3226],
            ['currency_code' => 'GHS', 'conversion_from_base' => 5.8, 'conversion_to_base' => 0.1724],
            ['currency_code' => 'GIP', 'conversion_from_base' => 0.73, 'conversion_to_base' => 1.3699],
            ['currency_code' => 'GMD', 'conversion_from_base' => 50.0, 'conversion_to_base' => 0.0200],
            ['currency_code' => 'GNF', 'conversion_from_base' => 9800.0, 'conversion_to_base' => 0.0001020],
            ['currency_code' => 'GTQ', 'conversion_from_base' => 7.7, 'conversion_to_base' => 0.1299],
            ['currency_code' => 'GYD', 'conversion_from_base' => 209.0, 'conversion_to_base' => 0.0048],
            ['currency_code' => 'HKD', 'conversion_from_base' => 7.78, 'conversion_to_base' => 0.1285],
            ['currency_code' => 'HNL', 'conversion_from_base' => 24.0, 'conversion_to_base' => 0.0417],
            ['currency_code' => 'HRK', 'conversion_from_base' => 6.4, 'conversion_to_base' => 0.1563],
            ['currency_code' => 'HTG', 'conversion_from_base' => 96.0, 'conversion_to_base' => 0.0104],
            ['currency_code' => 'HUF', 'conversion_from_base' => 300.0, 'conversion_to_base' => 0.00333],
            ['currency_code' => 'IDR', 'conversion_from_base' => 14150.0, 'conversion_to_base' => 0.0000707],
            ['currency_code' => 'ILS', 'conversion_from_base' => 3.25, 'conversion_to_base' => 0.3077],
            ['currency_code' => 'INR', 'conversion_from_base' => 74.0, 'conversion_to_base' => 0.0135],
            ['currency_code' => 'IQD', 'conversion_from_base' => 1460.0, 'conversion_to_base' => 0.0006849],
            ['currency_code' => 'IRR', 'conversion_from_base' => 42000.0, 'conversion_to_base' => 0.0000238],
            ['currency_code' => 'ISK', 'conversion_from_base' => 125.0, 'conversion_to_base' => 0.0080],
            ['currency_code' => 'JMD', 'conversion_from_base' => 150.0, 'conversion_to_base' => 0.0067],
            ['currency_code' => 'JOD', 'conversion_from_base' => 0.71, 'conversion_to_base' => 1.4085],
            ['currency_code' => 'JPY', 'conversion_from_base' => 110.0, 'conversion_to_base' => 0.0091],
            ['currency_code' => 'KES', 'conversion_from_base' => 109.0, 'conversion_to_base' => 0.00917],
            ['currency_code' => 'KGS', 'conversion_from_base' => 84.0, 'conversion_to_base' => 0.01190],
            ['currency_code' => 'KHR', 'conversion_from_base' => 4050.0, 'conversion_to_base' => 0.000247],
            ['currency_code' => 'KMF', 'conversion_from_base' => 411.0, 'conversion_to_base' => 0.00243],
            ['currency_code' => 'KPW', 'conversion_from_base' => 900.0, 'conversion_to_base' => 0.00111],
            ['currency_code' => 'KRW', 'conversion_from_base' => 1150.0, 'conversion_to_base' => 0.00087],
            ['currency_code' => 'KWD', 'conversion_from_base' => 0.30, 'conversion_to_base' => 3.3333],
            ['currency_code' => 'KYD', 'conversion_from_base' => 0.83, 'conversion_to_base' => 1.2048],
            ['currency_code' => 'KZT', 'conversion_from_base' => 425.0, 'conversion_to_base' => 0.00235],
            ['currency_code' => 'LAK', 'conversion_from_base' => 9400.0, 'conversion_to_base' => 0.0001064],
            ['currency_code' => 'LBP', 'conversion_from_base' => 1500.0, 'conversion_to_base' => 0.00067],
            ['currency_code' => 'LKR', 'conversion_from_base' => 200.0, 'conversion_to_base' => 0.0050],
            ['currency_code' => 'LRD', 'conversion_from_base' => 160.0, 'conversion_to_base' => 0.00625],
            ['currency_code' => 'LSL', 'conversion_from_base' => 15.0, 'conversion_to_base' => 0.0667],
            ['currency_code' => 'LYD', 'conversion_from_base' => 4.45, 'conversion_to_base' => 0.2247],
            ['currency_code' => 'MAD', 'conversion_from_base' => 9.0, 'conversion_to_base' => 0.1111],
            ['currency_code' => 'MDL', 'conversion_from_base' => 17.5, 'conversion_to_base' => 0.0571],
            ['currency_code' => 'MGA', 'conversion_from_base' => 3750.0, 'conversion_to_base' => 0.0002667],
            ['currency_code' => 'MKD', 'conversion_from_base' => 50.0, 'conversion_to_base' => 0.0200],
            ['currency_code' => 'MMK', 'conversion_from_base' => 2100.0, 'conversion_to_base' => 0.0004762],
            ['currency_code' => 'MNT', 'conversion_from_base' => 2850.0, 'conversion_to_base' => 0.0003509],
            ['currency_code' => 'MOP', 'conversion_from_base' => 8.0, 'conversion_to_base' => 0.1250],
            ['currency_code' => 'MRU', 'conversion_from_base' => 36.0, 'conversion_to_base' => 0.0278],
            ['currency_code' => 'MUR', 'conversion_from_base' => 40.0, 'conversion_to_base' => 0.0250],
            ['currency_code' => 'MVR', 'conversion_from_base' => 15.5, 'conversion_to_base' => 0.0645],
            ['currency_code' => 'MWK', 'conversion_from_base' => 800.0, 'conversion_to_base' => 0.00125],
            ['currency_code' => 'MXN', 'conversion_from_base' => 20.0, 'conversion_to_base' => 0.0500],
            ['currency_code' => 'MXV', 'conversion_from_base' => 1.0, 'conversion_to_base' => 1.0],
            ['currency_code' => 'MYR', 'conversion_from_base' => 4.2, 'conversion_to_base' => 0.2381],
            ['currency_code' => 'MZN', 'conversion_from_base' => 63.0, 'conversion_to_base' => 0.01587],
            ['currency_code' => 'NAD', 'conversion_from_base' => 15.0, 'conversion_to_base' => 0.0667],
            ['currency_code' => 'NGN', 'conversion_from_base' => 410.0, 'conversion_to_base' => 0.00244],
            ['currency_code' => 'NIO', 'conversion_from_base' => 35.0, 'conversion_to_base' => 0.0286],
            ['currency_code' => 'NOK', 'conversion_from_base' => 8.7, 'conversion_to_base' => 0.1149],
            ['currency_code' => 'NPR', 'conversion_from_base' => 117.0, 'conversion_to_base' => 0.00855],
            ['currency_code' => 'NZD', 'conversion_from_base' => 1.40, 'conversion_to_base' => 0.7143],
            ['currency_code' => 'OMR', 'conversion_from_base' => 0.38, 'conversion_to_base' => 2.6316],
            ['currency_code' => 'PAB', 'conversion_from_base' => 1.0, 'conversion_to_base' => 1.0],
            ['currency_code' => 'PEN', 'conversion_from_base' => 3.80, 'conversion_to_base' => 0.2632],
            ['currency_code' => 'PGK', 'conversion_from_base' => 3.5, 'conversion_to_base' => 0.2857],
            ['currency_code' => 'PHP', 'conversion_from_base' => 50.0, 'conversion_to_base' => 0.0200],
            ['currency_code' => 'PKR', 'conversion_from_base' => 160.0, 'conversion_to_base' => 0.00625],
            ['currency_code' => 'PLN', 'conversion_from_base' => 3.8, 'conversion_to_base' => 0.2632],
            ['currency_code' => 'PYG', 'conversion_from_base' => 6800.0, 'conversion_to_base' => 0.0001471],
            ['currency_code' => 'QAR', 'conversion_from_base' => 3.64, 'conversion_to_base' => 0.2747],
            ['currency_code' => 'RON', 'conversion_from_base' => 4.1, 'conversion_to_base' => 0.2439],
            ['currency_code' => 'RSD', 'conversion_from_base' => 104.0, 'conversion_to_base' => 0.00962],
            ['currency_code' => 'RUB', 'conversion_from_base' => 74.0, 'conversion_to_base' => 0.01351],
            ['currency_code' => 'RWF', 'conversion_from_base' => 980.0, 'conversion_to_base' => 0.00102],
            ['currency_code' => 'SAR', 'conversion_from_base' => 3.75, 'conversion_to_base' => 0.2667],
            ['currency_code' => 'SBD', 'conversion_from_base' => 8.0, 'conversion_to_base' => 0.1250],
            ['currency_code' => 'SCR', 'conversion_from_base' => 14.0, 'conversion_to_base' => 0.0714],
            ['currency_code' => 'SDG', 'conversion_from_base' => 437.0, 'conversion_to_base' => 0.00229],
            ['currency_code' => 'SEK', 'conversion_from_base' => 8.7, 'conversion_to_base' => 0.1149],
            ['currency_code' => 'SGD', 'conversion_from_base' => 1.34, 'conversion_to_base' => 0.7463],
            ['currency_code' => 'SHP', 'conversion_from_base' => 0.73, 'conversion_to_base' => 1.3699],
            ['currency_code' => 'SLL', 'conversion_from_base' => 11000.0, 'conversion_to_base' => 0.0000909],
            ['currency_code' => 'SOS', 'conversion_from_base' => 580.0, 'conversion_to_base' => 0.001724],
            ['currency_code' => 'SRD', 'conversion_from_base' => 21.0, 'conversion_to_base' => 0.0476],
            ['currency_code' => 'SSP', 'conversion_from_base' => 130.0, 'conversion_to_base' => 0.0077],
            ['currency_code' => 'STN', 'conversion_from_base' => 22.0, 'conversion_to_base' => 0.0455],
            ['currency_code' => 'SVC', 'conversion_from_base' => 8.75, 'conversion_to_base' => 0.1143],
            ['currency_code' => 'SYP', 'conversion_from_base' => 2512.0, 'conversion_to_base' => 0.000398],
            ['currency_code' => 'SZL', 'conversion_from_base' => 15.0, 'conversion_to_base' => 0.0667],
            ['currency_code' => 'THB', 'conversion_from_base' => 33.0, 'conversion_to_base' => 0.0303],
            ['currency_code' => 'TJS', 'conversion_from_base' => 11.3, 'conversion_to_base' => 0.0885],
            ['currency_code' => 'TMT', 'conversion_from_base' => 3.5, 'conversion_to_base' => 0.2857],
            ['currency_code' => 'TND', 'conversion_from_base' => 2.8, 'conversion_to_base' => 0.3571],
            ['currency_code' => 'TOP', 'conversion_from_base' => 2.3, 'conversion_to_base' => 0.4348],
            ['currency_code' => 'TRY', 'conversion_from_base' => 8.5, 'conversion_to_base' => 0.1176],
            ['currency_code' => 'TTD', 'conversion_from_base' => 6.8, 'conversion_to_base' => 0.1471],
            ['currency_code' => 'TWD', 'conversion_from_base' => 28.0, 'conversion_to_base' => 0.0357],
            ['currency_code' => 'TZS', 'conversion_from_base' => 2300.0, 'conversion_to_base' => 0.0004348],
            ['currency_code' => 'UAH', 'conversion_from_base' => 27.0, 'conversion_to_base' => 0.0370],
            ['currency_code' => 'UGX', 'conversion_from_base' => 3700.0, 'conversion_to_base' => 0.0002703],
            ['currency_code' => 'USD', 'conversion_from_base' => 1.0, 'conversion_to_base' => 1.0],
            ['currency_code' => 'USN', 'conversion_from_base' => 1.0, 'conversion_to_base' => 1.0],
            ['currency_code' => 'UYI', 'conversion_from_base' => 1.0, 'conversion_to_base' => 1.0],
            ['currency_code' => 'UYU', 'conversion_from_base' => 43.0, 'conversion_to_base' => 0.0233],
            ['currency_code' => 'UYW', 'conversion_from_base' => 1.0, 'conversion_to_base' => 1.0],
            ['currency_code' => 'UZS', 'conversion_from_base' => 10500.0, 'conversion_to_base' => 0.0000952],
            ['currency_code' => 'VES', 'conversion_from_base' => 4.0, 'conversion_to_base' => 0.2500],
            ['currency_code' => 'VND', 'conversion_from_base' => 23000.0, 'conversion_to_base' => 0.0000435],
            ['currency_code' => 'VUV', 'conversion_from_base' => 110.0, 'conversion_to_base' => 0.0091],
            ['currency_code' => 'WST', 'conversion_from_base' => 2.5, 'conversion_to_base' => 0.4000],
            ['currency_code' => 'XAF', 'conversion_from_base' => 550.0, 'conversion_to_base' => 0.001818],
            ['currency_code' => 'XCD', 'conversion_from_base' => 2.7, 'conversion_to_base' => 0.3704],
            ['currency_code' => 'XDR', 'conversion_from_base' => 0.71, 'conversion_to_base' => 1.4085],
            ['currency_code' => 'XOF', 'conversion_from_base' => 550.0, 'conversion_to_base' => 0.001818],
            ['currency_code' => 'XPF', 'conversion_from_base' => 100.0, 'conversion_to_base' => 0.0100],
            ['currency_code' => 'XSU', 'conversion_from_base' => 1.0, 'conversion_to_base' => 1.0],
            ['currency_code' => 'XUA', 'conversion_from_base' => 1.0, 'conversion_to_base' => 1.0],
            ['currency_code' => 'YER', 'conversion_from_base' => 250.0, 'conversion_to_base' => 0.0040],
            ['currency_code' => 'ZAR', 'conversion_from_base' => 15.0, 'conversion_to_base' => 0.0667],
            ['currency_code' => 'ZMW', 'conversion_from_base' => 20.0, 'conversion_to_base' => 0.0500],
            ['currency_code' => 'ZWL', 'conversion_from_base' => 322.0, 'conversion_to_base' => 0.0031],
        ];

        foreach ($data as $currency) {
            DB::table('currencies')
                ->where('currency_code', $currency['currency_code'])
                ->update([
                    'conversion_from_base' => $currency['conversion_from_base'],
                    'conversion_to_base'   => $currency['conversion_to_base'],
                ]);
        }
    }
}
